### PR TITLE
ENH: standardize mirror RTD implementations

### PR DESCRIPTION
**Pull request by nrwslac**
## Description

- update MR3/4K2 mirror RTD implementations to match TMO. 

## Motivation and Context

- KBO mirrors using the same pcds device so updating them all at once makes sense.

## How Has This Been Tested?

running on PLC, tested by viewing PCDS device typhos screen.

## Where Has This Been Documented?

https://jira.slac.stanford.edu/browse/ECS-6705

## Screenshots (if appropriate):
KBs-mirror-temp

## Pre-merge checklist
- [ ] Code works interactively
- [ ] Code contains descriptive comments
- [ ] Test suite passes locally
- [ ] Libraries are set to fixed versions and not ``Always Newest``
- [ ] Code committed with ``pre-commit`` (alternatively ``pre-commit run --all-files``)

### CODE REVIEW

**Review by ghalym — DISMISSED** [review]

**Comment by KaushikMalapati** [comment]
@nrwslac , do you want to tack on the change to SL1K2 from https://jira.slac.stanford.edu/browse/ECS-6745 in this pr? I don't think I can suggest the change since that file wasn't edited in branch, but the change would be in https://github.com/pcdshub/lcls-plc-rixs-optics/blob/5fd4dcb0de2eb38c32546617937faa5a90c9ec35/lcls-plc-rixs-optics/rixs_optics/POUs/PRG_SL1K2_EXIT.TcPOU#L82
alongside an ioc rebuild.

**Comment by nrwslac** [comment]
@KaushikMalapati yea, I can add that to this PR.

**Comment by nrwslac** [comment]
I'll fix the SL1K2 pv name in the next pull request.

**Review by jyotiphy — APPROVED** [review]
looks good to me

**Pull request merged**
