### PR TITLE
Maintenance Performed by Axilon

### PR DESCRIPTION
**Pull request by ZLLentz**
@nrwslac 

Has the updates needed for the switch
Additionally disables the RIX in-hutch mirrors (powered off) but that should be reverted or sync grouped

### CODE REVIEW

**Comment by nrwslac** [comment]
I see M2/3/4K2 Disabled, position offset changed for g_pi_upstream, and g_pi encoder link to channel 1, since channel 2 will be replaced.

**Comment by nrwslac** [comment]
I'll keep the work for the maintenance performed by Axilon on this branch until it is checkout out, then ill merge. This pull requests covers re-linking the Grating Pitch to the upstream encoder, removing the old down stream encoder, replacing the down stream encoder with a high rate encoder, and replacing the grating horizontal stage complete with new encoder readhead.

**Comment by ZLLentz** [comment]
Should we merge this soon?

**Comment by nrwslac** [comment]
> Should we merge this soon?



> Should we merge this soon?

I planned to wait until the checkout was complete in case some small changed to the PLC are needed. We did however run into a small issue that kicked off a new PJB. That being said, if someone needs to work on the this project, I can merge it.

**Comment by ZLLentz** [comment]
Ok, no rush- I'm just digging through github notifications today and saw this one hanging out

**Comment by nrwslac** [comment]
Checkout was complete, will merge.

**Pull request merged**
