### PR TITLE
MNT/FIX: MR3K2 RTD install [ECS-1789]

### PR DESCRIPTION
**Pull request by klauer**
## Description
Full description / story listed here: https://jira.slac.stanford.edu/browse/ECS-1789

## Motivation and Context
*   Two RTDs were installed for the chin guard of MR3K2 (these were in the design, intended to be read out by the MR3K2 bender rail upstream/downstream channels. They were noted to be "new" RTDs initially, causing some confusion)
*   One of two existing RTDs for the bender mirror was not reading back properly
*    Received request to advise on connections of RTDs and then check out MR3K2 and ensure that all systems were go
*    Additionally, help with limit switch verification, help setting hard stops was requested

## How Has This Been Tested?
Interactively, through EPICS, and with an abbreviated checkout procedure.

## Where Has This Been Documented?
This PR text and the linked Jira story.

RTDs reading out:

```
$ caget MR3K2:KBH:RTD:BEND:{U,D}S:{1,2,3}_RBV.VAL
MR3K2:KBH:RTD:BEND:US:1_RBV.VAL 19.26      <-- upstream bender actuator RTD
MR3K2:KBH:RTD:BEND:US:2_RBV.VAL 327.67     <-- nothing
MR3K2:KBH:RTD:BEND:US:3_RBV.VAL 19.38      <-- chin guard RTD 1

MR3K2:KBH:RTD:BEND:DS:1_RBV.VAL 19.31      <-- downstream bender actuator RTD
MR3K2:KBH:RTD:BEND:DS:2_RBV.VAL 19.35      <-- chin guard RTD 2
MR3K2:KBH:RTD:BEND:DS:3_RBV.VAL 327.67     <-- nothing
```

## Screenshots (if appropriate):

The channels are not as one would expect (due to a variety of reasons not worth explaining here):

image

image

## Pre-merge checklist
- [x] Code works interactively
- [x] Code contains descriptive comments
- [x] Code committed with ``pre-commit`` (alternatively ``pre-commit run --all-files``)

### CODE REVIEW

**Comment by nrwslac** [comment]
- I see soft limits changed for MR3K2 Bender US and DS.
- I did re-name the PVs to denote chin guard and there orientation on MR4K2 like this: `MR4K2:KBV:RTD:CHIN:L` do we know which ones left and right as looking down beam? I am not sure this is super important other than when the device is updated, will want the names to be generic.

**Comment by klauer** [comment]
> I did re-name the PVs to denote chin guard and their orientation on MR4K2 like this: MR4K2:KBV:RTD:CHIN:L do we know which ones left and right as looking down beam?

No, if you look in the Jira issue, there were just too many errors in pinouts and mistaken feedthrough swaps to figure out which was which. Then the chamber got buttoned up and that was that.

**Comment by nrwslac** [comment]
> > I did re-name the PVs to denote chin guard and their orientation on MR4K2 like this: MR4K2:KBV:RTD:CHIN:L do we know which ones left and right as looking down beam?
> 
> No, if you look in the Jira issue, there were just too many errors in pinouts and mistaken feedthrough swaps to figure out which was which. Then the chamber got buttoned up and that was that.

Yea, it looks like you went through the Optics wringer. I salute you sir. I think in this case it would make sense to denote one left and one right for PV sanity sake and make a note somewhere that  for this particular mirror it may be wrong. wdy think?

**Comment by klauer** [comment]
> I think in this case it would make sense to denote one left and one right for PV sanity sake and make a note somewhere that for this particular mirror it may be wrong.

Yeah, I think that sounds reasonable 👍 50/50 chance of being right, after all...

**Review by nrwslac — APPROVED** [review]
lgtm, I updated the chin guard RTDs to match others.

**Pull request merged**
